----Write a SQL QUERY TO FIND OUT THE EMPLOYEE those salaries are greater than the DEPT Budget 
--along with the salary difference ----------------


CREATE TABLE DEPT
(DEPTNO NUMERIC(2),
DNAME VARCHAR(14),
LOC VARCHAR(13),
SAL BIGINT)


INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK',1000)
INSERT INTO DEPT VALUES (20, 'RESEARCH', 'DALLAS',20000)
INSERT INTO DEPT VALUES (30, 'SALES', 'CHICAGO',30000)
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON',40000)
INSERT INTO DEPT VALUES (99, 'Developer', 'BBSR',1200)




SELECT * FROM DEPT
SELECT * FROM EMP
GO
--DROP TABLE DEPT


WITH CTE1 AS
(SELECT DEPTNO,ENAME,EMPNO,SUM (SAL) OVER (PARTITION BY EMPNO,DEPTNO) 'Employee_Salary'  FROM EMP ),
CTE2 AS 
(
SELECT DEPTNO,SUM (DEPTBUDGET) OVER (PARTITION BY DEPTNO) 'DEPT WHOLE BUDGET' FROM DEPT
)

SELECT CTE1.ENAME,CTE2.DEPTNO ,CTE1. [Employee_Salary],CTE2.[DEPT WHOLE BUDGET],


CONCAT(  FLOOR(((CTE1.Employee_Salary-CTE2.[DEPT WHOLE BUDGET])/(CTE1.Employee_Salary)) * 100),'%') 'Salary Difference'

FROM CTE1 
INNER JOIN CTE2 ON CTE1.DEPTNO=CTE2.DEPTNO
WHERE CTE1.Employee_Salary >= CTE2.[DEPT WHOLE BUDGET]

---------------------------------------------end-------------------


