--SQL intreview series 12
---Asked in most of intreview million dolar question
---No of rows/record generated by different types of join
---Joining Concept 

USE SSIS
----- Table script--------------------
--drop table table_A;
create table table_A
(id int);

--drop table table_B;
create table table_B
(id int);

insert into table_A values (1),(1),(1),(1),(1),(null),(null);
insert into table_B values (1),(1),(1),(2),(null);


--------START---------------------------------
SELECT * FROM table_A;
SELECT * FROM table_B;


----------->>>INNER JOIN/JOIN -------->>>

---INNER JOIN=Common record present in both the table----

SELECT table_A.id as 'A_id',table_B.id as 'B_id' FROM table_A
INNER JOIN table_B ON table_A.id=table_B.id 




----------->>>LEFT JOIN/LEFT OUTER JOIN -------->>>
---LEFT JOIN = inner join + fetch additional record present in left table  & not present  in right table 

SELECT table_A.id as 'A_id',table_B.id as 'B_id' FROM table_A
LEFT JOIN table_B ON table_A.id=table_B.id 



----------->>>RIGHT JOIN/RIGHT OUTER JOIN -------->>>
---RIGHT JOIN = inner join+fetch additional record present in right table  & not present  in left table 

SELECT table_A.id as 'A_id',table_B.id as 'B_id' FROM table_A
RIGHT JOIN table_B ON table_A.id=table_B.id 


----------->>>FULL JOIN/OUTER JOIN -------->>>

---FULL JOIN = inner join + fetch additional record present in left table  & not present  in right table --LEFT JOIN
 -->                       + fetch additional record present in right table & not present  in left table --RIGHT JOIN 

SELECT table_A.id as 'A_id',table_B.id as 'B_id' FROM table_A
 FULL JOIN table_B ON table_A.id=table_B.id 




 ----------->>>CROSS JOIN ------->>>

---CROSS JOIN = Each row from left table will match with each row of  right table irrespective to the value (catesian product)
--                      There is no joining condition 
 

SELECT table_A.id as 'A_id',table_B.id as 'B_id' FROM table_A
 CROSS  JOIN table_B 



  ----------->>>NATURAL JOIN-------->>>

---NATURAL JOIN = INNER JOIN (if  same  column is present on both the table )
--              = CROSS JOIN (if  same  column is NOT  present on both the table )
 

SELECT table_A.id as 'A_id',table_B.id as 'B_id' FROM table_A
 NATURAL JOIN table_B 





